name: ci

on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  build-test:
    runs-on: ubuntu-latest
    env:
      PYTHONPATH: ${{ github.workspace }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install deps
        run: |
          python -m pip install --upgrade pip
          if [ -f requirements.txt ]; then pip install -r requirements.txt; else pip install -r requisitos.txt; fi

      - name: Run tests
        run: pytest -q

      # === Notificação Datadog ===
      - name: Notify Datadog (US5)
        if: always()    # roda mesmo se os testes falharem
        env:
          DD_API_KEY: ${{ secrets.DD_API_KEY }}   # Settings > Secrets > Actions
          DD_SITE:    ${{ secrets.DD_SITE }}      # us5.datadoghq.com  (sem https)
          GITHUB_STATUS: ${{ job.status }}
          REPO: ${{ github.repository }}
          RUN_ID: ${{ github.run_id }}
        run: |
          set -euo pipefail

          # normaliza site (remove https:// e / finais)
          SITE="${DD_SITE#https://}"
          SITE="${SITE%/}"

          STATUS="${GITHUB_STATUS:-success}"
          ALERT="success"
          if [ "$STATUS" != "success" ]; then ALERT="error"; fi

          TITLE="CI • ${REPO} • build-test"
          TEXT="GitHub Actions run #${RUN_ID} finalizado com status: ${STATUS}"

          # monta JSON com jq (já vem no runner ubuntu)
          PAYLOAD=$(jq -n --arg title "$TITLE" --arg text "$TEXT" --arg alert "$ALERT" --arg repo "$REPO" \
            '{title:$title, text:$text, alert_type:$alert, tags:["source:github","env:ci",("repo:"+$repo)]}')

          echo "Datadog host: api.${SITE}"
          curl -sS -X POST "https://api.${SITE}/api/v1/events" \
            -H "Content-Type: application/json" \
            -H "DD-API-KEY: ${DD_API_KEY}" \
            --data "$PAYLOAD" \
            -o /tmp/dd_resp.json -w "HTTP_STATUS:%{http_code}\n"

          echo "Resposta:"
          cat /tmp/dd_resp.json || true


      echo "Resposta Datadog:"
      cat /tmp/dd_resp.json || true
